import TestList from './TestList'
import TestItem from './TestItem'
import TestActions from './TestActions'
import TestDummy from './TestDummy'

export {TestList, TestItem, TestActions, TestDummy}

export const
  TEST_LIST_FETCH = 'TEST_LIST_FETCH',
  TEST_LIST_FETCH_FULFILLED = 'TEST_LIST_FETCH_FULFILLED',
  TEST_LIST_FETCH_REJECTED = 'TEST_LIST_FETCH_REJECTED',
  TEST_ITEM_FETCH = 'TEST_ITEM_FETCH',
  TEST_ITEM_FETCH_FULFILLED = 'TEST_ITEM_FETCH_FULFILLED',
  TEST_ITEM_FETCH_REJECTED = 'TEST_ITEM_FETCH_REJECTED',
  TEST_ITEMS_SWAP = 'TEST_ITEMS_SWAP',
  TEST_ITEMS_SWAP_FULFILLED = 'TEST_ITEMS_SWAP_FULFILLED',
  TEST_ITEMS_SWAP_REJECTED = 'TEST_ITEMS_SWAP_REJECTED'