import TestList from './TestList'
import TestItem from './TestItem'
import TestActions from './TestActions'

export {TestList, TestItem, TestActions}

export const
  TEST_LIST_FETCH = 'TEST_LIST_FETCH',
  TEST_LIST_FETCH_FULLFILLED = 'TEST_LIST_FETCH_FULLFILLED',
  TEST_LIST_FETCH_REJECTED = 'TEST_LIST_FETCH_REJECTED',
  TEST_ITEM_FETCH = 'TEST_ITEM_FETCH',
  TEST_ITEM_FETCH_FULLFILLED = 'TEST_ITEM_FETCH_FULLFILLED',
  TEST_ITEM_FETCH_REJECTED = 'TEST_ITEM_FETCH_REJECTED',
  TEST_ITEMS_SWAP = 'TEST_ITEMS_SWAP',
  TEST_ITEMS_SWAP_FULLFILLED = 'TEST_ITEMS_SWAP_FULLFILLED',
  TEST_ITEMS_SWAP_REJECTED = 'TEST_ITEMS_SWAP_REJECTED'