import LyricsActions from './LyricsActions'
import LyricsList from './LyricsList'
import LyricsItem from './LyricsItem'

export {LyricsActions, LyricsList, LyricsItem}

export const
  LYRICS_LIST_FETCH = 'LYRICS_LIST_FETCH',
  LYRICS_LIST_FETCH_FULLFILLED = 'LYRICS_LIST_FETCH_FULLFILLED',
  LYRICS_LIST_FETCH_REJECTED = 'LYRICS_LIST_FETCH_REJECTED',
  LYRICS_ITEM_FETCH = 'LYRICS_ITEM_FETCH',
  LYRICS_ITEM_FETCH_FULLFILLED = 'LYRICS_ITEM_FETCH_FULLFILLED',
  LYRICS_ITEM_FETCH_REJECTED = 'LYRICS_ITEM_FETCH_REJECTED'
