import AuthorList from './AuthorList'
import AuthorItem from './AuthorItem'
import AuthorActions from './AuthorActions'

export {AuthorList, AuthorItem, AuthorActions}

export const
  AUTHOR_LIST_FETCH = 'AUTHOR_LIST_FETCH',
  AUTHOR_LIST_FETCH_PENDING = 'AUTHOR_LIST_FETCH_PENDING',
  AUTHOR_LIST_FETCH_FULFILLED = 'AUTHOR_LIST_FETCH_FULFILLED',
  AUTHOR_LIST_FETCH_REJECTED = 'AUTHOR_LIST_FETCH_REJECTED',
  AUTHOR_ITEMS_SWAP = 'AUTHOR_ITEMS_SWAP',
  AUTHOR_ITEMS_SWAP_PENDING = 'AUTHOR_ITEMS_SWAP_PENDING',
  AUTHOR_ITEMS_SWAP_FULFILLED = 'AUTHOR_ITEMS_SWAP_FULFILLED',
  AUTHOR_ITEMS_SWAP_REJECTED = 'AUTHOR_ITEMS_SWAP_REJECTED',
  AUTHOR_ITEM_FETCH = 'AUTHOR_ITEM_FETCH',
  AUTHOR_ITEM_FETCH_PENDING = 'AUTHOR_ITEM_FETCH_PENDING',
  AUTHOR_ITEM_FETCH_FULFILLED = 'AUTHOR_ITEM_FETCH_FULFILLED',
  AUTHOR_ITEM_FETCH_REJECTED = 'AUTHOR_ITEM_FETCH_REJECTED'