import Login from './Login'
import Dashboard from './Dashboard'
import Profile from './Profile'

export {Login, Dashboard, Profile}

export const
  USER_UPDATE = 'USER_UPDATE',
  USER_SAVE = 'USER_SAVE', // TODO: find better name
  USER_SAVE_FULLFILLED = 'USER_SAVE_FULLFILLED', // TODO: find better name
  USER_SAVE_REJECTED = 'USER_SAVE_REJECTED', // TODO: find better name
  USER_REMOVE = 'USER_REMOVE',
  USER_AUTH = 'USER_AUTH',
  USER_AUTH_FULLFILLED = 'USER_AUTH_FULLFILLED',
  USER_AUTH_REJECTED = 'USER_AUTH_REJECTED',
  USER_UNAUTH = 'USER_UNAUTH',
  USER_UNAUTH_FULLFILLED = 'USER_UNAUTH_FULLFILLED',
  USER_UNAUTH_REJECTED = 'USER_UNAUTH_REJECTED',
  USER_AUTH_ERROR = 'USER_AUTH_ERROR',
  USER_AUTH_CHECK = 'USER_AUTH_CHECK',
  USER_AUTH_CHECK_SUCCESS = 'USER_AUTH_CHECK_SUCCESS',
  USER_AUTH_CHECK_FAILURE = 'USER_AUTH_CHECK_FAILURE'