import Login from './Login'
import Dashboard from './Dashboard'

export {Login, Dashboard}

export const
  AUTH_USER = 'AUTH_USER',
  AUTH_USER_FULLFILLED = 'AUTH_USER_FULLFILLED',
  UNAUTH_USER = 'UNAUTH_USER',
  UNAUTH_USER_FULLFILLED = 'UNAUTH_USER_FULLFILLED',
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_CHECK = 'AUTH_CHECK',
  AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS',
  AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE'