import GenreList from './GenreList'
import GenreItem from './GenreItem'
import GenreEditor from './GenreEditor'
import GenreCreator from './GenreCreator'
import GenreActions from './GenreActions'

export {GenreList, GenreItem, GenreActions, GenreEditor, GenreCreator}

export const
  GENRE_LIST_FETCH = 'GENRE_LIST_FETCH',
  GENRE_LIST_FETCH_PENDING = 'GENRE_LIST_FETCH_PENDING',
  GENRE_LIST_FETCH_FULFILLED = 'GENRE_LIST_FETCH_FULFILLED',
  GENRE_LIST_FETCH_REJECTED = 'GENRE_LIST_FETCH_REJECTED',
  GENRE_ITEM_FETCH = 'GENRE_ITEM_FETCH',
  GENRE_ITEM_FETCH_FULFILLED = 'GENRE_ITEM_FETCH_FULFILLED',
  GENRE_ITEM_FETCH_REJECTED = 'GENRE_ITEM_FETCH_REJECTED',
  GENRE_ITEM_ADD = 'GENRE_ITEM_ADD',
  GENRE_ITEM_ADD_FULFILLED = 'GENRE_ITEM_ADD_FULFILLED',
  GENRE_ITEM_ADD_REJECTED = 'GENRE_ITEM_ADD_REJECTED',
  GENRE_ITEM_SAVE = 'GENRE_ITEM_SAVE',
  GENRE_ITEM_SAVE_FULFILLED = 'GENRE_ITEM_SAVE_FULFILLED',
  GENRE_ITEM_SAVE_REJECTED = 'GENRE_ITEM_SAVE_REJECTED',
  GENRE_ITEM_UPDATE = 'GENRE_ITEM_UPDATE',
  GENRE_ITEM_UPDATE_FULFILLED = 'GENRE_ITEM_UPDATE_FULFILLED',
  GENRE_ITEM_UPDATE_REJECTED = 'GENRE_ITEM_UPDATE_REJECTED',
  GENRE_ITEM_REMOVE = 'GENRE_ITEM_REMOVE',
  GENRE_ITEM_REMOVE_FULFILLED = 'GENRE_ITEM_REMOVE_FULFILLED',
  GENRE_ITEM_REMOVE_REJECTED = 'GENRE_ITEM_REMOVE_REJECTED'