import ArtistList from './ArtistList'
import ArtistItem from './ArtistItem'
import ArtistActions from './ArtistActions'

export {ArtistList, ArtistItem, ArtistActions}

export const
  ARTIST_LIST_FETCH = 'ARTIST_LIST_FETCH',
  ARTIST_LIST_FETCH_PENDING = 'ARTIST_LIST_FETCH_PENDING',
  ARTIST_LIST_FETCH_FULFILLED = 'ARTIST_LIST_FETCH_FULFILLED',
  ARTIST_LIST_FETCH_REJECTED = 'ARTIST_LIST_FETCH_REJECTED',
  ARTIST_ITEMS_SWAP = 'ARTIST_ITEMS_SWAP',
  ARTIST_ITEMS_SWAP_PENDING = 'ARTIST_ITEMS_SWAP_PENDING',
  ARTIST_ITEMS_SWAP_FULFILLED = 'ARTIST_ITEMS_SWAP_FULFILLED',
  ARTIST_ITEMS_SWAP_REJECTED = 'ARTIST_ITEMS_SWAP_REJECTED',
  ARTIST_ITEM_FETCH = 'ARTIST_ITEM_FETCH',
  ARTIST_ITEM_FETCH_PENDING = 'ARTIST_ITEM_FETCH_PENDING',
  ARTIST_ITEM_FETCH_FULFILLED = 'ARTIST_ITEM_FETCH_FULFILLED',
  ARTIST_ITEM_FETCH_REJECTED = 'ARTIST_ITEM_FETCH_REJECTED'