import ArtistList from './ArtistList'
import ArtistItem from './ArtistItem'
import ArtistActions from './ArtistActions'

export {ArtistList, ArtistItem, ArtistActions}

export const
  ARTIST_LIST_FETCH = 'ARTIST_LIST_FETCH',
  ARTIST_LIST_FETCH_FULLFILLED = 'ARTIST_LIST_FETCH_FULLFILLED',
  ARTIST_LIST_FETCH_REJECTED = 'ARTIST_LIST_FETCH_REJECTED',
  ARTIST_ITEMS_SWAP = 'ARTIST_ITEMS_SWAP',
  ARTIST_ITEMS_SWAP_FULLFILLED = 'ARTIST_ITEMS_SWAP_FULLFILLED',
  ARTIST_ITEMS_SWAP_REJECTED = 'ARTIST_ITEMS_SWAP_REJECTED',
  ARTIST_ITEM_FETCH = 'ARTIST_ITEM_FETCH',
  ARTIST_ITEM_FETCH_FULLFILLED = 'ARTIST_ITEM_FETCH_FULLFILLED',
  ARTIST_ITEM_FETCH_REJECTED = 'ARTIST_ITEM_FETCH_REJECTED'