export const
  APP_SET_TARGET_ROUTE = 'APP_SET_TARGET_ROUTE',
  APP_UNSET_TARGET_ROUTE = 'APP_UNSET_TARGET_ROUTE',
  APP_START_PROCESSING = 'APP_START_PROCESSING',
  APP_END_PROCESSING = 'APP_END_PROCESSING',
  APP_ERROR_OCCURRED = 'APP_ERROR_OCCURRED',
  APP_ERROR_HIDE = 'APP_ERROR_HIDE',
  APP_NOTIFICATION_OCCURRED = 'APP_NOTIFICATION_OCCURRED',
  APP_NOTIFICATION_HIDE = 'APP_NOTIFICATION_HIDE'
