import {takeEvery, put, all} from 'redux-saga/effects'

import {
  APP_START_PROCESSING,
  APP_END_PROCESSING,
} from './AppActionTypes'

import {
  GENRE_LIST_FETCH,
  GENRE_LIST_FETCH_FULLFILLED,
  GENRE_LIST_FETCH_REJECTED,
  GENRE_ITEM_FETCH,
  GENRE_ITEM_FETCH_FULLFILLED,
  GENRE_ITEM_FETCH_REJECTED,
  GENRE_ITEM_SAVE,
  GENRE_ITEM_SAVE_FULLFILLED,
  GENRE_ITEM_SAVE_REJECTED,
  GENRE_ITEM_UPDATE,
  GENRE_ITEM_UPDATE_FULLFILLED,
  GENRE_ITEM_UPDATE_REJECTED,
  GENRE_ITEM_REMOVE,
  GENRE_ITEM_REMOVE_FULLFILLED,
  GENRE_ITEM_REMOVE_REJECTED,
} from '../genre/Genre'

import {
  LYRICS_LIST_FETCH,
  LYRICS_LIST_FETCH_FULLFILLED,
  LYRICS_LIST_FETCH_REJECTED,
  LYRICS_ITEM_FETCH,
  LYRICS_ITEM_FETCH_FULLFILLED,
  LYRICS_ITEM_FETCH_REJECTED,
} from '../lyrics/Lyrics'

import {
  AUTHOR_LIST_FETCH,
  AUTHOR_LIST_FETCH_FULLFILLED,
  AUTHOR_LIST_FETCH_REJECTED,
  AUTHOR_ITEM_FETCH,
  AUTHOR_ITEM_FETCH_FULLFILLED,
  AUTHOR_ITEM_FETCH_REJECTED,
} from '../author/Author'

import {
  ARTIST_LIST_FETCH,
  ARTIST_LIST_FETCH_FULLFILLED,
  ARTIST_LIST_FETCH_REJECTED,
  ARTIST_ITEM_FETCH,
  ARTIST_ITEM_FETCH_FULLFILLED,
  ARTIST_ITEM_FETCH_REJECTED,
} from '../artist/Artist'

import {
  USER_AUTH,
  USER_AUTH_FULLFILLED,
  USER_AUTH_REJECTED,
  USER_UNAUTH,
  USER_UNAUTH_FULLFILLED,
  USER_UNAUTH_REJECTED,
  USER_AUTH_CHECK,
  USER_AUTH_CHECK_SUCCESS,
  USER_AUTH_CHECK_FAILURE,
  USER_SAVE,
  USER_SAVE_FULLFILLED,
  USER_SAVE_REJECTED,
} from '../user/User'

export function* runTheSpinner() {
  yield put({type: APP_START_PROCESSING})
}

export function* stopTheSpinner() {
  yield put({type: APP_END_PROCESSING})
}

export function* watchTheSpinner() {
  yield takeEvery([
    GENRE_ITEM_REMOVE,
    GENRE_ITEM_UPDATE,
    GENRE_ITEM_SAVE,
    GENRE_ITEM_FETCH,
    GENRE_LIST_FETCH,
    USER_AUTH,
    USER_UNAUTH,
    USER_AUTH_CHECK,
    USER_SAVE,
    LYRICS_LIST_FETCH,
    LYRICS_ITEM_FETCH,
    AUTHOR_LIST_FETCH,
    AUTHOR_ITEM_FETCH,
    ARTIST_LIST_FETCH,
    ARTIST_ITEM_FETCH,
  ], runTheSpinner)

  yield takeEvery([
    GENRE_LIST_FETCH_FULLFILLED,
    GENRE_LIST_FETCH_REJECTED,
    GENRE_ITEM_FETCH_FULLFILLED,
    GENRE_ITEM_FETCH_REJECTED,
    GENRE_ITEM_SAVE_FULLFILLED,
    GENRE_ITEM_SAVE_REJECTED,
    GENRE_ITEM_UPDATE_FULLFILLED,
    GENRE_ITEM_UPDATE_REJECTED,
    GENRE_ITEM_REMOVE_FULLFILLED,
    GENRE_ITEM_REMOVE_REJECTED,
    USER_SAVE_FULLFILLED,
    USER_SAVE_REJECTED,
    USER_AUTH_CHECK_SUCCESS,
    USER_AUTH_CHECK_FAILURE,
    USER_AUTH_FULLFILLED,
    USER_AUTH_REJECTED,
    USER_UNAUTH_FULLFILLED,
    USER_UNAUTH_REJECTED,
    LYRICS_LIST_FETCH_FULLFILLED,
    LYRICS_LIST_FETCH_REJECTED,
    LYRICS_ITEM_FETCH_FULLFILLED,
    LYRICS_ITEM_FETCH_REJECTED,
    AUTHOR_LIST_FETCH_FULLFILLED,
    AUTHOR_LIST_FETCH_REJECTED,
    AUTHOR_ITEM_FETCH_FULLFILLED,
    AUTHOR_ITEM_FETCH_REJECTED,
    ARTIST_LIST_FETCH_FULLFILLED,
    ARTIST_LIST_FETCH_REJECTED,
    ARTIST_ITEM_FETCH_FULLFILLED,
    ARTIST_ITEM_FETCH_REJECTED,
  ], stopTheSpinner)
}

export default function* rootSaga() {
  yield all([
    watchTheSpinner(),
  ])
}