import SongEditor from './SongEditor'

export {SongEditor}

export const
  SONG_ITEM_SAVE = 'SONG_ITEM_SAVE',
  SONG_ITEM_SAVE_FULLFILLED = 'SONG_ITEM_SAVE_FULLFILLED',
  SONG_ITEM_SAVE_REJECTED = 'SONG_ITEM_SAVE_REJECTED',
  SONG_ITEM_UPDATE = 'SONG_ITEM_UPDATE',
  SONG_ITEM_UPDATE_FULLFILLED = 'SONG_ITEM_UPDATE_FULLFILLED',
  SONG_ITEM_UPDATE_REJECTED = 'SONG_ITEM_UPDATE_REJECTED',
  SONG_ITEM_REMOVE = 'SONG_ITEM_REMOVE',
  SONG_ITEM_REMOVE_FULLFILLED = 'SONG_ITEM_REMOVE_FULLFILLED',
  SONG_ITEM_REMOVE_REJECTED = 'SONG_ITEM_REMOVE_REJECTED',
  SONG_ITEM_FETCH = 'SONG_ITEM_FETCH',
  SONG_ITEM_FETCH_FULLFILLED = 'SONG_ITEM_FETCH_FULLFILLED',
  SONG_ITEM_FETCH_REJECTED = 'SONG_ITEM_FETCH_REJECTED'
