import SongEditor from './SongEditor'

export {SongEditor}

export const ADD_SONG = 'ADD_SONG',
  ADD_SONG_FULLFILLED = 'ADD_SONG_FULLFILLED',
  ADD_SONG_REJECTED = 'ADD_SONG_REJECTED',
  UPDATE_SONG = 'UPDATE_SONG',
  FETCH_SONG = 'FETCH_SONG',
  FETCH_SONG_FULLFILLED = 'FETCH_SONG_FULLFILLED',
  FETCH_SONG_REJECTED = 'FETCH_SONG_REJECTED',
  REMOVE_SONG = 'REMOVE_SONG',
  REMOVE_SONG_FULLFILLED = 'REMOVE_SONG_FULLFILLED',
  REMOVE_SONG_REJECTED = 'REMOVE_SONG_REJECTED'
