import RecordList from './RecordList'
import RecordItem from './RecordItem'
import RecordActions from './RecordActions'

export {RecordList, RecordItem, RecordActions}

export const
  FETCH_RECORD_LIST = 'FETCH_RECORD_LIST',
  FETCH_RECORD_LIST_FULLFILLED = 'FETCH_RECORD_LIST_FULLFILLED',
  FETCH_RECORD_LIST_REJECTED = 'FETCH_RECORD_LIST_REJECTED',
  FETCH_RECORD_ITEM = 'FETCH_RECORD_ITEM',
  FETCH_RECORD_ITEM_FULLFILLED = 'FETCH_RECORD_ITEM_FULLFILLED',
  FETCH_RECORD_ITEM_REJECTED = 'FETCH_RECORD_ITEM_REJECTED'
